version: 2
aliases:
  - &install-node-dependencies
    |
      yarn

defaults: &defaults
  working_directory: ~/IgniteApp
jobs:
  test-ios:
    <<: *defaults
    macos:
      xcode: "9.0"

    steps:
      - checkout
      - run:
          name: Load dependencies
          command:
            |
              brew update
              brew tap wix/brew
              brew install --HEAD applesimutils
              npm install -g detox-cli
      - run: *install-node-dependencies
      - run: detox build -c ios.sim.debug
      - run: detox test -c ios.sim.debug

  test-js:
    <<: *defaults
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - run: *install-node-dependencies
      - run: npm test

workflows:
  version: 2

  build:
    jobs:
      # - test-js
      - test-ios
